import { DecoderPlugin } from '../DecoderPlugin';
import { DecodeResult, Message, Options } from '../DecoderPluginInterface';
import { ResultFormatter } from '../utils/result_formatter';
import { DateTimeUtils } from '../DateTimeUtils';

/**
 * Label 10 — INI (Flight Initialisation) sub-format
 *
 * Downlink generated by British Airways (and possibly other operators) at
 * ACARS system startup / flight initialisation. The body starts with a
 * `:INI` preamble and carries time, origin, destination, a pair of
 * two-digit counters, an operator-internal token, optional padding, and
 * a trailing reference token (often an RNAV waypoint).
 *
 * Wire format:
 *
 *   : INI 1220 EGLL EIDW 01 01 SUTXS       HOLYR
 *   | |   |    |    |    |  |  |     |     |
 *   | |   |    |    |    |  |  |     |     └── Trailing reference token (waypoint / crew ID / ops code)
 *   | |   |    |    |    |  |  |     └──────── Fixed-width padding (typ. 6 spaces — often a blank flight number field)
 *   | |   |    |    |    |  |  └────────────── Operator-internal system / terminal / CMU ID
 *   | |   |    |    |    |  └───────────────── Sub-sequence / leg counter (2 digits) — wild guess semantics
 *   | |   |    |    |    └──────────────────── Sequence / message counter (2 digits) — wild guess semantics
 *   | |   |    |    └───────────────────────── Destination airport ICAO
 *   | |   |    └────────────────────────────── Origin airport ICAO
 *   | |   └─────────────────────────────────── Time of report HHMM UTC
 *   | └─────────────────────────────────────── Sub-label `INI` (initialisation)
 *   └───────────────────────────────────────── Leading `:` separator
 *
 * The `01 01` counters, the operator-internal token, and the trailing
 * reference are surfaced verbatim without invented semantics per the
 * analyst's wild-guess classification.
 */
export class Label_10_INI extends DecoderPlugin {
  name = 'label-10-ini';

  qualifiers() {
    return {
      labels: ['10'],
      preambles: [':INI'],
    };
  }

  decode(message: Message, options: Options = {}): DecodeResult {
    const decodeResult = this.initResult(
      message,
      'Flight Initialisation (INI)',
    );

    const text = message.text || '';
    if (!text) {
      this.setDecodeLevel(decodeResult, false);
      return decodeResult;
    }

    // :INI HHMM OOOO DDDD NN NN TOKEN<padding>REFTOKEN
    // Fields are fixed-width and concatenated (no delimiters):
    //   :        1 char   (literal)
    //   INI      3 chars  (literal)
    //   time     4 chars  HHMM
    //   origin   4 chars  ICAO
    //   dest     4 chars  ICAO
    //   seq1     2 chars  digits
    //   seq2     2 chars  digits
    //   token1   6 chars  alphanumeric (may include trailing spaces)
    //   padding  (variable) spaces
    //   reftok   remainder (non-space token)
    const re =
      /^:INI(?<time>\d{4})(?<origin>[A-Z]{4})(?<dest>[A-Z]{4})(?<seq1>\d{2})(?<seq2>\d{2})(?<token1>[A-Z0-9]{1,8})(?<pad>\s+)(?<reftok>\S+)\s*$/;
    const m = text.match(re);
    if (!m?.groups) {
      this.setDecodeLevel(decodeResult, false);
      return decodeResult;
    }

    const { time, origin, dest, seq1, seq2, token1, reftok } = m.groups;

    // Validate HHMM ranges
    if (Number(time.substring(0, 2)) > 23 || Number(time.substring(2, 4)) > 59) {
      this.setDecodeLevel(decodeResult, false);
      return decodeResult;
    }

    // ── raw ──
    ResultFormatter.timestamp(
      decodeResult,
      DateTimeUtils.convertHHMMSSToTod(time + '00'),
    );
    ResultFormatter.departureAirport(decodeResult, origin);
    ResultFormatter.arrivalAirport(decodeResult, dest);
    decodeResult.raw.sequence_1 = seq1;
    decodeResult.raw.sequence_2 = seq2;
    decodeResult.raw.system_token = token1;
    decodeResult.raw.reference_token = reftok;

    // ── formatted ──
    decodeResult.formatted.items.unshift(
      {
        type: 'message_type',
        code: 'MSGTYP',
        label: 'Message Type',
        value: 'Flight Initialisation (INI)',
      },
      {
        type: 'sublabel',
        code: 'SUBLBL',
        label: 'Sub-Label',
        value: ':INI',
      },
    );
    decodeResult.formatted.items.push(
      {
        type: 'time',
        code: 'TIME',
        label: 'Time (UTC, HHMM)',
        value: `${time.substring(0, 2)}:${time.substring(2, 4)}`,
      },
      {
        type: 'sequence_1',
        code: 'SEQ1',
        label: 'Sequence Counter 1',
        value: seq1,
      },
      {
        type: 'sequence_2',
        code: 'SEQ2',
        label: 'Sequence Counter 2',
        value: seq2,
      },
      {
        type: 'system_token',
        code: 'SYSTOK',
        label: 'System / Terminal Token',
        value: token1,
      },
      {
        type: 'reference_token',
        code: 'REFTOK',
        label: 'Reference Token (waypoint / ops code)',
        value: reftok,
      },
    );

    this.setDecodeLevel(decodeResult, true, 'full');
    return decodeResult;
  }
}
